# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nazov', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nazov akcie/ochutnavky', max_length=20, unique=True)),
                ('date_from', models.DateTimeField(blank=True, help_text='datum a cas zaciatku akcie', null=True)),
                ('date_to', models.DateTimeField(blank=True, help_text='datum a cas konca akcie', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nazov skupiny', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='mnozstvo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='meno zakaznika alebo nazov stola', max_length=60)),
                ('done', models.BooleanField(default=False, help_text='vybavena objednavka')),
                ('event', models.ForeignKey(blank=True, help_text='akcia / ochutnavka', on_delete=django.db.models.deletion.CASCADE, to='inventory.Event')),
                ('items', models.ManyToManyField(blank=True, help_text='vybrane produkty na akcii / ochutnavke', to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='titulok fotky', max_length=120)),
                ('blob', models.FileField(blank=True, upload_to=b'/static/data/')),
                ('uuid', models.CharField(blank=True, default='', max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='kod tovaru (skladovy)', max_length=20, unique=True)),
                ('origin_name', models.CharField(help_text='hruby nazov tovaru (skladovy)', max_length=60)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='cena tovaru', max_digits=5, null=True)),
                ('is_new', models.BooleanField(default=True, help_text='produkt bol prave synchrnonizovany')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False, help_text='aktivne zobrazenie v tablete')),
                ('name', models.CharField(blank=True, help_text='nazov pre zobrazenie v tablete', max_length=120)),
                ('description', models.TextField(blank=True, help_text='popis produktu')),
                ('size', models.DecimalField(blank=True, decimal_places=2, help_text='objem/jednotka', max_digits=5, null=True)),
                ('is_wine', models.BooleanField(default=False, help_text='je produkt vino')),
                ('group', models.ForeignKey(blank=True, help_text='skupina', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Group')),
                ('photos', models.ManyToManyField(help_text='fotky produktu', to='inventory.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='kod typu produktu', max_length=20)),
                ('name', models.CharField(help_text='nazov typu produktu', max_length=120)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_inventory.specification_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('RED', 'cervene'), ('WHITE', 'biele'), ('ROSE', 'ruzove')], help_text='farba vina', max_length=5)),
                ('year', models.IntegerField(blank=True, default='', help_text='rocnik', null=True)),
                ('attribute', models.CharField(blank=True, choices=[('SV', 'Stolove vino'), ('AV', 'Akostne vino'), ('KV', 'Kabinetne vino'), ('NZ', 'Neskory zber'), ('VH', 'Vyber z hrozna'), ('BV', 'Bobulovy vyber'), ('HV', 'Hrozienkovy vyber'), ('SV', 'Slamove vino'), ('LV', 'Ladove vino'), ('VC', 'Vyber z cibeb')], help_text='privlastok', max_length=5)),
                ('locality', models.CharField(blank=True, default='', help_text='lokalita', max_length=60)),
                ('sugar_content', models.CharField(blank=True, default='', help_text='cukornatost', max_length=20)),
                ('alcohol', models.CharField(blank=True, default='', help_text='alkohol', max_length=20)),
                ('sugar_residual', models.CharField(blank=True, choices=[('DY', 'suche'), ('HD', 'polosuche'), ('HS', 'polosladke'), ('SW', 'sladke')], help_text='zbytkovy cukor', max_length=2)),
                ('acidity', models.CharField(blank=True, default='', help_text='celkove kyseliny', max_length=20)),
                ('awards', models.ManyToManyField(blank=True, help_text='medaily/ocenenia', to='inventory.Award')),
                ('product', models.ForeignKey(help_text='produkt', on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(help_text='vybrany produkt', on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='event',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='vyber produktov na ochutnavke/akcii', to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='award',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='mala fotka medaily/ocenenia', on_delete=django.db.models.deletion.CASCADE, to='inventory.Photo'),
        ),
    ]
