# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(help_text='fotky produktu', to='inventory.Photo'),
        ),
    ]
