# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160325_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='n\xe1zov pre zobrazenie v\xa0tablete', max_length=120),
        ),
    ]
