# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='photo',
            name='blob',
            field=models.FileField(blank=True, upload_to='/home/morientes/Work/tp-soft/winecart/src/inventory/static/data/'),
        ),
    ]
