# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160325_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, help_text='akt\xedvne zobrazenie v\xa0tablete'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='awards',
            field=models.ManyToManyField(blank=True, help_text='medaily/ocenenia', null=True, to='inventory.Award'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, help_text='ro\u010dn\xedk', null=True),
        ),
    ]
