# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160420_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='acidity',
            field=models.CharField(blank=True, default='', help_text='celkov\xe9 kyseliny', max_length=20),
        ),
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=models.CharField(blank=True, default='', help_text='alkohol', max_length=20),
        ),
        migrations.AlterField(
            model_name='wine',
            name='awards',
            field=models.ManyToManyField(blank=True, help_text='medaily/ocenenia', to='inventory.Award'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='locality',
            field=models.CharField(blank=True, default='', help_text='lokalita', max_length=60),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sugar_content',
            field=models.CharField(blank=True, default='', help_text='cukornatost', max_length=20),
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, default='', help_text='ro\u010dn\xedk', null=True),
        ),
    ]
