# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160605_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='fotky produktu', to='inventory.Photo'),
        ),
    ]
