# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160612_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='wine',
            field=models.ForeignKey(blank=True, help_text='wine', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Wine'),
        ),
    ]
