# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160706_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='serving',
            field=models.CharField(blank=True, default='', help_text='servirovanie', max_length=255),
        ),
    ]
