# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_wine_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, default=0, help_text='mnozstvo', null=True),
        ),
    ]
