# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blob',
            field=models.ImageField(blank=True, upload_to='/home/morientes/Work/tp-soft/winecart/src/inventory/static/data/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_wine',
            field=models.BooleanField(default=True, help_text='je produkt vino'),
        ),
    ]
