# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160717_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ForeignKey(blank=True, help_text='fotky produktu', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Photo'),
        ),
    ]
