# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20160717_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blob',
            field=models.FileField(blank=True, upload_to='image_/%Y/%m/%d'),
        ),
    ]
