# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20160721_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ForeignKey(blank=True, help_text='obrazok skupiny', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Photo'),
        ),
    ]
