# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='place',
            field=models.IntegerField(blank=True, default=0, help_text='poradie na stranke', null=True),
        ),
    ]
