# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_group_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, help_text='rocnik', null=True),
        ),
    ]
