# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20160722_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_detail',
            field=models.CharField(blank=True, default='', help_text='kontaktne informacie - adresa', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, help_text='akcia / ochutnavka', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='telefonny kontakt', max_length=20, null=True),
        ),
    ]
