# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20160725_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S1', 'unit price')], help_text='typ nastavenia', max_length=2)),
                ('value', models.CharField(help_text='hodnota nastavenia', max_length=60)),
            ],
        ),
    ]
