# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(choices=[('SETTING_1', 'unit price')], help_text='typ nastavenia', max_length=20),
        ),
    ]
