# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20160801_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='type',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='value',
        ),
        migrations.AddField(
            model_name='setting',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='jednotkove mnozstvo', max_digits=5, null=True),
        ),
    ]
