# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20160801_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
