# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20160801_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='UserPreference',
        ),
    ]
